export declare const DEFAULT_CLI_HOME = '.xnate-cli';
export declare const NPM_NAME = '@xnate-cli/core';
export declare const DEPENDENCIES_PATH = 'dependencies';
export declare const CWD: string;
export declare const XNATE_CONFIG: any;
export declare const SRC_DIR: any;
export declare const SRC_DIR_COMPONENTS: any;
export declare const ES_DIR: any;
export declare const LIB_DIR: any;
export declare const UMD_DIR: any;
export declare const TYPES_DIR: any;
export declare const ROOT_DOCS_DIR: any;
export declare const ROOT_PAGES_DIR: any;
export declare const ESLINT_EXTENSIONS: string[];
export declare const VITE_RESOLVE_EXTENSIONS: string[];
export declare const SCRIPTS_EXTENSIONS: string[];
export declare const PUBLIC_DIR_INDEXES: string[];
export declare const STYLE_DIR_NAME = 'style';
export declare const EXAMPLE_DIR_NAME = 'example';
export declare const LOCALE_DIR_NAME = 'locale';
export declare const DOCS_DIR_NAME = 'docs';
export declare const DIR_INDEX = 'index.vue';
export declare const TESTS_DIR_NAME = '__tests__';
export declare const GENERATORS_DIR: any;
export declare const UI_PACKAGE_JSON: any;
export declare const CLI_PACKAGE_JSON: any;
export declare const SITE: any;
export declare const SITE_OUTPUT_PATH: any;
export declare const SITE_PUBLIC_PATH: any;
export declare const SITE_DIR: any;
export declare const SITE_PC_DIR: any;
export declare const SITE_PC_ROUTES: any;
export declare const SITE_MOBILE_ROUTES: any;
export declare const SITE_CONFIG: any;
